# Nome do fluxo de trabalho (workflow)
name: Generate Snake Animation

# Define quando a Action deve ser executada
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

# Define as tarefas que serão executadas
jobs:
  build:
    # ADICIONE ESTA PERMISSÃO AQUI!
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      # Passo 1: Clona o repositório para que a Action possa acessá-lo
      - uses: actions/checkout@v3

      # Passo 2: Roda a Action "snk" que gera a animação da cobrinha
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # O ID do seu usuário no GitHub. Este comando pega automaticamente.
          github_user_name: ${{ github.repository_owner }}
          
          # Lista de arquivos de saída que serão gerados
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.svg?palette=ocean
      
      # Passo 3: Envia os arquivos gerados de volta para o repositório
      - name: Push to repository
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
